### ISSUE TITLE
Исправить ошибки при регистрации нового пользователя

### ISSUE THREAD

**Issue by sayonara-sama** [LARP-Platform-Team/larp-platform#52]
Данные для регистрации, вызывающие ошибку:
- логин - admin
- имя - admin
- e-mail - admin@a.ru
- пароль - пароль
- повторите пароль - пароль

На локальном компе результат выглядит так:
![img_05102015_223617](https://cloud.githubusercontent.com/assets/2082734/10291480/a5e63494-6bb2-11e5-94c6-9e5b514efb62.png)

На сервере - так:
![img_05102015_223709](https://cloud.githubusercontent.com/assets/2082734/10291481/a5fb96b8-6bb2-11e5-9e23-018232130afc.png)

Нужно это исправить и выводить нормальные сообщения об ошибках.

**Comment by treble-snake** [comment]
Проверить еще раз после завершение #63

**Comment by treble-snake** [comment]
Похоже, задача #63 решила дело.
